### ISSUE TITLE
OPTV automatically adding .ori extension to orientation files in main parameters

### ISSUE THREAD

**Issue by jmha273** [OpenPTV/openptv-python#47]
This error can be replicated by using the test_cavity found on OpenPTV's github page.
Open OPTV software like usual
Right click a run>main parameters>click "OK"
Click Start>init/restart

After this, a .ori extension is added to the end of the "calibration data for image" field that is in the general tab of main parameters. 

This may be repeated; each iteration adding another .ori to the end of the field.

This applies to all test folders I've tried.

My current operating systems that this happens on are
Ubuntu 12.04 LTS 64-bit
Ubuntu 14.04 LTS 32-bit

James

**Comment by alexlib** [comment]
@jmha273 please test the fix

**Comment by jmha273** [comment]
I just completely removed and reinstalled the master branches of openptv and openptv-python. 
I am still experiencing the issue with the added .ori extension in the same manner as before. (Ubuntu 12.04 tested)

**Comment by alexpub** [comment]
Hi, 
please unzip and place the attached jw_ptv.c file into your openptv-python/src_c folder and run again

`python setup.py build_ext -I/usr/local/include -L/usr/local/lib`
`python setup.py install`

then please after you press init check that there is a print like this: 

`Debugging
cal/cam1.tif.ori
cal/cam1.tif.ori`

It is possible that before you need to open Main Parameters and fix the situation in the folder that was already affected, i.e. remove all but one `.ori` extension (i.e. `cam1.tif.ori` is the right name) 

[jw_ptv.c.zip](https://github.com/OpenPTV/openptv-python/files/430374/jw_ptv.c.zip)

**Comment by alexlib** [comment]
Hi, 
@jmha273 please unzip and place the attached jw_ptv.c file into your openptv-python/src_c folder and run again

`python setup.py build_ext -I/usr/local/include -L/usr/local/lib`
`python setup.py install`

then please after you press init check that there is a print like this: 

`Debugging
cal/cam1.tif.ori
cal/cam1.tif.ori`

It is possible that before you need to open Main Parameters and fix the situation in the folder that was already affected, i.e. remove all but one `.ori` extension (i.e. `cam1.tif.ori` is the right name) 

[jw_ptv.c.zip](https://github.com/OpenPTV/openptv-python/files/430374/jw_ptv.c.zip)

**Comment by alexlib** [comment]
no, it's wrong. I see it - the problem persists. I keep digging

**Comment by alexlib** [comment]
ok, another attempt: 

please extract the attached file: 

`jw_ptv.c` to `../src_c`
and 
`parameter.py` to `pyptv_gui`

and test it again 

@jmha273  - thanks

**Comment by jmha273** [comment]
Okay, I will do that once my older version is done with the current test
file.

Is this the same as switching to the debug_print_ori_issue branch?

**Comment by alexlib** [comment]
yes, it is the same as cloning the openptv branch and switching to this branch. Note that I updated it again in the last hour.

**Comment by alexlib** [comment]
closed, solved in https://github.com/OpenPTV/openptv-python/pull/48
