### ISSUE TITLE
sortgrid seems to have a problem

### ISSUE THREAD

**Issue by alexlib** [OpenPTV/openptv-python#49]
both my recent tests of the packages from the users on the forum have raised a concern about sortgrid - it appears all wrong for the first camera. second and other cameras look fine. 

@yosefm - have you experienced something of this kind? #

**Comment by yosefm** [comment]
No, but I use sortgrid from liboptv. If there is a test folder I can take a look tomorrow.

**Comment by alexlib** [comment]
all the tests passed, so i close this issue
