### ISSUE TITLE
Unable to run the first test

### ISSUE THREAD

**Issue by josephcaburnay** [OpenPTV/openptv-python#56]
Greetings!

I am trying to run openptv for the first time. I followed the installation instruction but I failed in the `make verify` part. So instead of building it in Ubuntu 16.04, I decided to run your provided virtual machine. Though I was able to install everything successfully, I am getting this error: 

![iccp-warning](https://user-images.githubusercontent.com/3245568/28528676-afad2040-708e-11e7-8f63-f80ac6ba17c6.PNG)

I did pull the latest repo then followed the instruction after pulling, but I still received this iCCP warning message. It appears that the test doesn't continue after encountering the message.

**Comment by josephcaburnay** [comment]
I am now able to run the pyGUI. The installation procedure works in Ubuntu 16.04, but installing `chaco` without removing `scikit-image` is a little tricky in the latest Anaconda2 distribution.

**Comment by alexlib** [comment]
Thanks for an update. Can you please explain how do you install chaco and why did you have to remove scikit-image?

**Comment by alexlib** [comment]
the ICCP warning is something we cannot resolve, it belongs to wxPython set of problems. If you change the ETS_TOOLKIT=qt4 
this won't happen
